-- SQLite
SELECT e.ID, e.NAME, e.PHONE_NUMBER, e.CONTRACT_DATE, e.POSITION_ID FROM EMPLOYEES AS e
INNER JOIN LOCATIONS ON (LOCATIONS.EMPLOYEE_ID = e.ID)
GROUP BY e.ID HAVING COUNT(LOCATIONS.EMPLOYEE_ID) >= 2; 
