-- SQLite
SELECT c.name, cr.name, e.name 
FROM LOCATIONS AS l
INNER JOIN CUSTOMERS as C ON(l.CUSTOMER_ID = c.ID)
INNER JOIN CARS as cr ON(l.CAR_ID = cr.ID)
INNER JOIN EMPLOYEES AS e ON(l.EMPLOYEE_ID = e.ID)